defaults:
  - dflt.yaml
  #- balance: dflt


in2mem: False

nworkers: ${dyn_nworkers:-1}
pinmem: True
pftch_fctr: 4
prstwrk: True


test:
  in2mem: False
  ## slowing cause usb troughput max out, better use low
  nworkers: ${dyn_nworkers:-1}
  pinmem: True
  pftch_fctr: 4
  prstwrk: True
