defaults:
  - dflt.yaml
  #- balance: dflt
  

in2mem: False

nworkers: ${dyn_nworkers:1} 
pinmem: False
#pftch_fctr: 1
prstwrk: False


test:
  in2mem: False

  nworkers: ${dyn_nworkers:1}  
  pinmem: False
  #pftch_fctr: 0
  prstwrk: False
