## SEGMENTATION
seg: 
  ## itp (interpolate) -> avg adj sel snippet feats
  ## the following two form the selorpad from XDV
  ## uni (uniformm) -> picks len idxs equally spaced trough linspace 
  ## seq (sequence) -> picks a sequence of len idx
  sel: ??? ## ucf: itp | xdv: seq
  len: ??? ## ucf: 32  | xdv: 200
  ## ON / OFF 
  jit: 0 ## jitter selection of adjacent idxs when sel is uni or itp (if feat nclips > len)
  rnd: 0 ## randomizes idxs of segmented features (each crop will have same indexing)


## CROPS
## set ncrops acording to data.frgb.ncrops and ds in use
## if -1: crops2use set to maximum
## 0 : feats in use must have no crops whatsoever, so fn are in format 'fn.npy'  
## 1 : feats in use have crop augm and only center crop is used, eg. 'fn__0.npy'
## 2 : feats in use have crop augm and center + topright (or wtv) eg. 'fn__0.npy' && 'fn__1.npy'
## ...
## if data has no crops , aut0set to 0
crops2use: 
  train: ${dyn_crops2use:${data.frgb.ncrops}, -1}
  test: ${dyn_crops2use:${data.frgb.ncrops}, -1}


## TODO: can be made open-world (ow) and we can further standard some dflts following OVVAD, etc
## Curriculum-ish Learning for XDV
## a list of entries from lbls.info under data/xdv
## to be removed from train set, based on the frist label of filenames
culum: ~ 
  #- B4.RIOT