# @package _global_

defaults:
  - dflt.yaml


hydra:
  job_logging:
    loggers:
      src.train:
        level: DEBUG
      src.model.pstfwd:
        level: DEBUG
      src.model.loss:
        level: DEBUG

model:
  epoch: 1

