# Common parameters for the PstFwdUtils
## ths class is used for for Infer class in each netwrk
## as well as an additional parameter for each Loss class
_target_: src.model.pstfwd.PstFwdUtils
_cfg:
  dvc: ${dvc}

  bs: ${dataload.bs}
  bal_abn_bag: ${dataload.balance.bag}
  ncrops: 
    - ${dataproc.crops2use.train}
    - ${dataproc.crops2use.test}
  seg_sel: ${dataproc.seg.sel}
  seg_len: ${dataproc.seg.len}

  ## static selection 
  k: 3
  do: 0.7
  
  ## SBS (SampleBatchSelection)
  sls_ratio: ${dyn_per_ds:${data.id}, 0.1, 0.2} ## ucf, xdv
  bls_ratio: ${dyn_per_ds:${data.id}, 0.2, 0.4} ## ucf, xdv