defaults:
  - _self_
  #- net: 
  #- optima: 
  #- lrs: 
  #- pstfwd: dflt
  #- loss@loss.{custom name}: {target .yml in loss/.. }

id: ???
epochs: ???
optima: ???



## glance
loss:
  glance:
    _target_: 
    min_mining_step: ${dyn_per_ds:${data.id},50,100}
    sigma: 0.1          
    alpha: 0.9  