defaults:
  - _dflt
  - pstfwd: dflt
  - optima: adam
  - lrs: null
  - loss@loss.normal: bn-score
  - loss@loss.mpp: bn-mpp

id: bndfm
epochs: 10

clipnorm: True

optima:
  lr: 0.0001
  weight_decay: 0.00005
