defaults:
  #- _self_ ## if anything need to be overide from net
  - net: mir
  - optima: adam
  - lrs: null
  #- _self_

epochs: 5

## ex
net:
  arch:
    _cfg:
      neurons: 
        - 1024
        - 32

optima:
  lr: 1.0e-3
  weight_decay: 1.0e-5

loss: 
  rnkg: 
    _target_: src.model.loss.rnkg.RankingLoss
    _cfg:
      bs: ${dl.loader.train.bs}
      seglen: ${dl.trnsfrm.train.len}
      lambda12: [8e-5,8e-5]
    
  #clas:
  #  _target_: src.model.loss.clas.Loss
  #  _cfg:
  #    fx: topk  ## topk wink full
  #    topk: 16
  #    wink: 3
  #    winkconv: false




