defaults:
  - _.yaml
  - net: mir
  - optima: adam
  - lrs: null
  #- _self_

epochs: 5

optima:
  lr: 1.0e-3
  weight_decay: 1.0e-5


loss: 
  rnkg: #${model.loss.rnkg}
    _target_: src.model.loss.rnkg.Loss
    _cfg:
      bs: ${dataloader.train.bs}
      seglen: ${datatrnsfrm.train.len}
      lambda12: [8e-5,8e-5]




