defaults:
  - _dflt
  - pstfwd: dflt
  - optima: adam
  - lrs: null
  - loss@loss.rnkg: rnkg
  
  #- loss: _dflt
  ###- loss: rnkg
  ##- loss@score: rnkg
  ##- loss@s1: rnkg
  ##- loss@s2: clas ## how 2 iterate trough each and what name as id 
  #- loss/rnkg@rnkg: 

  #- _self_

id: rank
epochs: 5
optima:
  lr: 0.0001
  weight_decay: 1.0e-5






