defaults:
  - _.yaml
  - net: mir  ## expose net in main
  - optima: adam
  - lrs: null
  
  ###- loss: rnkg
  ##- loss@score: rnkg
  ##- loss@s1: rnkg
  ##- loss@s2: clas ## how 2 iterate trough each and what name as id 
  #- loss/rnkg@rnkg: 

  #- _self_



epochs: 5

optima:
  lr: 1.0e-3
  weight_decay: 1.0e-5


loss: 
  rnkg: #${model.loss.rnkg}
    _target_: src.model.loss.score.Ranking
    _cfg:
      bs: ${dataload.train.bs}
      seglen: ${dataproc.seg.len}
      lambda12: [8e-5,8e-5]




