defaults:
  - _.yaml
  - net: rtfm
  - optima: adam
  - lrs: null
  - loss: null
  #- _self_

epochs: 5

optima:
  lr: 0.0001
  weight_decay: 0.0005

loss: 
  mgnt:
    _target_: src.model.loss.feat.Rtfm
    _cfg:
      alpha: 0.0001
      margin: 100

  bce:
    _target_: src.model.loss.score.Bce

  smooth: 
    _target_: src.model.loss.score.smooth

  spars:
    _target_: src.model.loss.score.sparsity


