_target_: "src.model.net.${model.net.id}.NetPstFwd"
_cfg: 
  dvc: ${dvc}
  bs: ${dataload.train.bs}
  ncrops: ${dataproc.crops2use}
  smp_bal: ${dataproc.sampler.balance}
  seg_sel: ${dataproc.seg.sel}
  seg_len: ${dataproc.seg.len}

  k: 3
  do: 0.7

  ## sbs sel strat train
  ## xdv
  sls_ratio: 0.2
  bls_ratio: 0.4
  ## ucf
  #sls_ratio: 0.1
  #bls_ratio: 0.2