defaults:
  - _self_

id: ??? ## must be specified as the main._target_ depends on
vrs: ""
wght_init: xavier0 

dryfwd: true
summary: true ## params/flops/actvs
profile: false

main:
  _target_: "src.model.net.${net.id}.Network${net.vrs}" 
  ## defaults this even if network dont have this option
  ## serves as a indicator in Validate.fwd to either save the attws or not
  ## then on each network with such, use dyn res (example in attnmil)
  #ret_att: False
fm: ~
cls: ~

## every network has its one inference class
infer:
  _target_: "src.model.net.${net.id}.Infer"
  _cfg: ~
