defaults:
  - _self_

id: ???
vrs: ""
wght_init: xavier0 

main:
  _target_: "src.model.net.${net.id}${net.vrs}.Network" 
  ## defaults this even if network dont have this option
  ## serves as a indicator in Validate.fwd to either save the attws or not
  ## then on each network with such, use dyn res (example in attnmil)
  #ret_att: False
fm: ~
cls: ~

infer:
  _target_: "src.model.net.${net.id}.Infer"
  _cfg: ~
