# @package _global_


defaults:
  - override /data/frgb: i3drocng
  - override /model: clas
  - override /net: mir 

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      dataload.balance.bag: 0.5, 0.55, 0.45, 0.7, 0.3

exp_name: dload
tags: ["dataload"]

  
model:
  epochs: 5
  optima:
    lr: 0.0001
  loss:
    clas:
      per_crop: False

dataproc: 
  seg:
    sel: seq
    len: 200

dataload:
  bs: 32
  #balance:
  #  bag: 0.3