# @package _global_


#defaults:
#  #- override /data: ucf_cliptsa  ## ucf_vadclip  ucf_i3drocng
#  - override /datatrnsfrm: mil_intrplt
#  - override /dataloader: low
#  - override /net: rtfm
#  - override /model: clas
#  - overide /net: mir
#  - override /vldt: dflt

hydra:
  mode: MULTIRUN
  sweeper:
    #grid_params:
    params:
      #net: mir, rtfm
      dataload.balance.bag: 0.5, 0.55
      #dataload.bs: 32

exp_name: dload
tags: ["dataload"]

  
model:
  epochs: 2
  optima:
    lr: 0.0001

#dataproc: 
#  seg:
#    sel: seq
#    len: 200

dataload:
  bs: 32