# Dataset preparation configuration

# List of datasets to download and prepare
datasets: [xd]  # Options: [ucf, xd]

# How to transfer files from temporary to final data directory
relocate_option: move # Options:
                      # move - Move files (delete from temporary after transfer)
                      # copy - Copy files (retain temporary copies)

# Cleaning strategy for temporary files
clean_option: 0       # Options:
                      # 0 - Do not clean temporary files
                      # 1 - Remove unzipped temporary files, keep original zip files
                      # 2 - Remove all temporary files including downloaded zips

ucf_urls:
  data/raw/UCF-Crime/UCF_Crimes.zip: 'https://www.crcv.ucf.edu/data1/chenchen/UCF_Crimes.zip'

xd_urls:
  data/raw/XD-Violence/Training_Videos_1.zip: 'https://stuxidianeducn-my.sharepoint.com/:u:/g/personal/pengwu_stu_xidian_edu_cn/ERiQQLUAex1CnwuBIEOK9YgBtcqU3hR_ZDtahCwLtVVkew?e=QHJ3bz'
  data/raw/XD-Violence/Training_Videos_2.zip: 'https://stuxidianeducn-my.sharepoint.com/:u:/g/personal/pengwu_stu_xidian_edu_cn/EU-CqR-yYmVEqlFR1qHs3ZwB_Xfmi9d2augzSoOgDM66ug?e=gNNLIR'
  data/raw/XD-Violence/Training_Videos_3.zip: 'https://stuxidianeducn-my.sharepoint.com/:u:/g/personal/pengwu_stu_xidian_edu_cn/EVcHk8zeeQJGhoDrsj1I-RsBXwGgOwrr_qU_8Yvx1KVnEw?e=84ftkC'
  data/raw/XD-Violence/Training_Videos_4.zip: 'https://stuxidianeducn-my.sharepoint.com/:u:/g/personal/pengwu_stu_xidian_edu_cn/EV9x2SOsTWNFjAAukYmTVIEBKTFz2rc_lkJ4N-8Y7AbIvA?e=fOZU2d'
  data/raw/XD-Violence/Training_Videos_5.zip: 'https://stuxidianeducn-my.sharepoint.com/:u:/g/personal/pengwu_stu_xidian_edu_cn/ERGkxZqFDJlGs4GM1CvhOY4B5ASIKQIS4elt3VWZqjR65g?e=jdbmcO'
  data/raw/XD-Violence/Test_Videos.zip: 'https://stuxidianeducn-my.sharepoint.com/:u:/g/personal/pengwu_stu_xidian_edu_cn/EdewYQSko-BHpew03RBfGLQBIAOUdF7jt1rC71rK5iBGag?e=v4Enay'
  data/raw/XD-Violence/Test_Annotations.zip: 'https://stuxidianeducn-my.sharepoint.com/:t:/g/personal/pengwu_stu_xidian_edu_cn/EVWktpfZoT1BqahOCzvie_UB6aeitUGU94aZDgydsQHTMw?e=fkRIr0'
