_target_: uws4vad.model.loss.feat.Rtfm
alpha: 0.0001
margin: 100
preproc: og

#smooth: 
#  _target_: uws4vad.model.loss.score.smooth
#spars:
#  _target_: uws4vad.model.loss.score.sparsity
#bce:
#  _target_: uws4vad.model.loss.score.Bce