## disable python warnings
no_warns: False
## ask for tags if none are provided in the config
enforce_tags: True

## pretty print config tree at the start of the run using Rich library
## 0 -> no print
## 1 -> prints dflts on utils.xtra
## >1 -> print all blocks
log_cfg: 11

vis:
  restart: False
  ## needle string to delete visdom env names
  ## all : delete every env
  ## always prompts to delete running env
  ## if deleted program exits, else continues
  delete: ~
