defaults:
  - _self_
  #- net: 
  #- optima: 
  #- lrs: 
  #- pstfwd: dflt
  #- loss@loss.{custom name}: {target .yml in loss/.. }

id: ???
epochs: ???
optima: ???

## glance
#loss:
#  glance:
#    _target_: uws4vad.model.loss.score.Glance
#    min_mining_step: ${dyn_per_ds:${data.id},50,100}
#    sigma: 0.1          
#    alpha: 0.9  

## ITP 
# [mir-clas-xdv--debug:src.data.traindl:309][DEBUG] - **** 118 ****
# [mir-clas-xdv--debug:src.data.traindl:313][DEBUG] - vid[118][RGB] (115, 768) float32  City.of.God.2002__#01-37-13_01-38-30_label_G-B2-0.npy
# [mir-clas-xdv--debug:src.data.traindl:407][DEBUG] - FSeg: grabbed intrplt 33 idxs
# [mir-clas-xdv--debug:src.data.traindl:318][DEBUG] - vid[118][RGB] PST-SEG (32, 768)
# [mir-clas-xdv--debug:src.data.traindl:220][ERROR] - [524]
# [mir-clas-xdv--debug:src.data.traindl:229][DEBUG] - Frame 524 → Feature idx 32.75 → Segment idx 9
# [mir-clas-xdv--debug:src.data.traindl:357][DEBUG] - vid[118] (32, 768) float32 seqlen=32 (32,)

## SELORPAD
# [mir-clas-xdv--debug:src.data.traindl:309][DEBUG] - **** 943 ****
# [mir-clas-xdv--debug:src.data.traindl:313][DEBUG] - vid[943][RGB] (52, 768) float32  v=5plpAWiJ9VA__#1_label_B4-0-0.npy
# [mir-clas-xdv--debug:src.data.traindl:413][DEBUG] - grabbed None idxs
# [mir-clas-xdv--debug:src.data.traindl:318][DEBUG] - vid[943][RGB] PST-SEG (200, 768)
# [mir-clas-xdv--debug:src.data.traindl:220][ERROR] - [108 341 711]
# [mir-clas-xdv--debug:src.data.traindl:229][DEBUG] - Frame 108 → Feature idx 6.75 → Segment idx 25
# [mir-clas-xdv--debug:src.data.traindl:229][DEBUG] - Frame 341 → Feature idx 21.3125 → Segment idx 81
# [mir-clas-xdv--debug:src.data.traindl:229][DEBUG] - Frame 711 → Feature idx 44.4375 → Segment idx 170
# [mir-clas-xdv--debug:src.data.traindl:357][DEBUG] - vid[943] (200, 768) float32 seqlen=52 (200,)