defaults:
  - _dflt
  - pstfwd: dflt
  - optima: adam
  - lrs: null
  - loss@loss.clas: clas
  - loss@loss.salient: salient
  #- _self_

id: clas2
epochs: 10
optima:
  lr: 0.0001
  weight_decay: 1.0e-5

